language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --no-suggest

script: vendor/bin/phpunit
